services:
  mariadb:
    image: mariadb:10.6
    container_name: mysql_music
    restart: always
    volumes:
      - music_db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - music_network
    env_file:
      - .env

  php:
    image: vekian/music:latest
    container_name: music
    environment:
      PHP_MEMORY_LIMIT: "512M"
    ports:
      - "9030:9000"
    volumes:
      - ./public:/var/www/music
    networks:
      - music_network
    env_file:
      - .env

volumes:
  music_db_data:

networks:
  music_network:
    name: music_network
